<?php
/**
 * @var $this Laminas\View\Renderer\PhpRenderer
 */
?>
<h1>Indicadores</h1>
<table>
<thead>
<tr>
<th>Indicador</th>
<th>&nbsp;</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr>
<td>Total de órgãos</td>
<td>&nbsp;</td>
<td><?=$this->total_orgaos?></td>
</tr>
<tr>
<td>Desenvolveu software livre</td>
<td>&nbsp;</td>
<td><?=$this->total_desenvolveu_floss  . ' (' . round($this->total_desenvolveu_floss/$this->total_orgaos*100,2) . '%)'?></td>
</tr>
<tr>
<td>Total de softwares</td>
<td>&nbsp;</td>
<td><?=$this->total_softwares_livres + $this->total_softwares_nao_livres?></td>
</tr>
<tr>
<td>Total de softwares livres</td>
<td>&nbsp;</td>
<td><?=$this->total_softwares_livres?></td>
</tr>
<tr>
<td>Total de softwares não livres</td>
<td>&nbsp;</td>
<td><?=$this->total_softwares_nao_livres?></td>
</tr>
<tr>
<td>Total de softwares livres usados</td>
<td>&nbsp;</td>
<td><?=$this->total_softwares_livres_usados?></td>
</tr>
<tr>
<td>Total de softwares não livres usados</td>
<td>&nbsp;</td>
<td><?=$this->total_softwares_nao_livres_usados?></td>
</tr>
</tbody>
</table>
<p>
<a href="<?=$this->url('home')?>">Homepage</a>
</p>